#!/usr/bin/env python
# EXAMPLE CODE BELOW

from map import *

context(ENGLAND)
fleet_move_failed('eng', 'mao')
fleet_move_failed('nth', 'bel')
fleet_hold('nor')
fleet_support_hold('nwg', 'nor')
army_move('pic', 'bre')
fleet_create('lvp')
set('nor')
set('bel')
set('bre')

context(ITALY)
set('tun')
fleet_hold('tun')
fleet_support_hold('tyr', 'tun')
army_move('ven', 'pie')
army_retreat('mar', 'gas')
set('gas')

context(FRANCE)
army_move('bur', 'par')
fleet_move('lyo', 'mar')
army_move_failed('naf', 'tun')
army_support_move('spa', 'lyo', 'mar')
fleet_move_failed('wes', 'mao')
destroy('naf')
set('naf')
set('spa')
set('por')

context(GERMANY)
fleet_move('bal', 'swe')
army_support_move('boh', 'trl', 'vie')
fleet_support_move('den', 'bal', 'swe')
army_move_failed('hol', 'bel')
army_move('trl', 'vie')
army_create('mun')
army_create('ber')
set('boh')
set('hol')
set('den')
set('vie')
set('swe')

context(RUSSIA)
army_move('gal', 'sil')
fleet_move('rum', 'sev')
army_move('stp', 'lvn')
army_move('war', 'pru')
army_support_move('bud', 'bul', 'ser')
fleet_retreat('swe', 'bot')
army_retreat('vie', 'gal')
destroy('sev')
set('sil')
set('gal')
set('pru')
set('bud')
set('rum')

context(AUSTRIA)
army_move('ser', 'gre')
army_move_failed('tri', 'vie')
destroy('alb')
set('gre')
set('alb')

context(TURKEY)
set('bul')
set('ser')
fleet_move('bla', 'con')
fleet_create('smy')
army_move('con', 'ank')
army_move('bul', 'ser')

done()
