#!/usr/bin/env python
# EXAMPLE CODE BELOW

from map import *

context(ENGLAND)
set('nor')
set('bel')
set('bre')
fleet_move('lvp', 'nao')
fleet_move_failed('eng', 'mao')
fleet_move('nwg', 'bar')
fleet_move_failed('nor', 'nth')
fleet_move_failed('nth', 'hol')
army_hold('bre')

context(ITALY)
set('tun')
set('gas')
army_move('pie', 'mar')
army_support_move('gas', 'pie', 'mar')
fleet_move('tun', 'ion')
fleet_move('tyr', 'lyo')

context(FRANCE)
fleet_move_failed('wes', 'mao')
army_move_failed('spa', 'mar')
army_move_failed('par', 'bre')
dislodge('mar')
set('naf')
set('spa')
set('por')

context(GERMANY)
army_hold('hol')
army_support_move('ber', 'mun', 'sil')
army_move_failed('boh', 'gal')
fleet_move_failed('den', 'bal')
army_move_failed('mun', 'sil')
fleet_hold('swe')
dislodge('vie')
set('boh')
set('hol')
set('den')
set('vie')
set('swe')

context(RUSSIA)
army_hold('lvn')
fleet_move_failed('bot', 'bal')
army_move_failed('pru', 'ber')
army_support_move('sil', 'gal', 'boh')
army_move_failed('gal', 'boh')
army_support_move('bud', 'tri', 'vie')
set('sil')
set('gal')
set('pru')
set('bud')
set('rum')

context(AUSTRIA)
army_move('tri', 'vie')
army_hold('gre')
set('gre')
set('alb')

context(TURKEY)
army_hold('ser')
army_move('ank', 'con')
fleet_move('con', 'aeg')
fleet_move('smy', 'eas')
set('bul')
set('ser')

done()
